=== yermochenko/epam-example-of-task3/vauchers.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.example.org/vauchers"
	xmlns:tns="http://www.example.org/vauchers" elementFormDefault="qualified">
	<element name="vauchers">
		<complexType>
			<sequence>
				<element name="vaucher" maxOccurs="unbounded">
					<complexType>
						<sequence>
							<element name="type" type="string" />
							<element name="country" type="string" />
							<element name="days">
								<complexType>
									<simpleContent>
										<extension base="int">
											<attribute name="nights" default="0">
												<simpleType>
													<restriction base="byte">
														<minInclusive value="-1" />
														<maxInclusive value="1" />
													</restriction>
												</simpleType>
											</attribute>
										</extension>
									</simpleContent>
								</complexType>
							</element>
							<element name="transport">
								<simpleType>
									<restriction base="string">
										<enumeration value="AVIA" />
										<enumeration value="RAILWAY" />
										<enumeration value="AUTO" />
										<enumeration value="SHIP" />
									</restriction>
								</simpleType>
							</element>
							<element name="cost" type="positiveInteger" />
							<element name="hotel-characteristics">
								<complexType>
									<sequence>
										<element name="stars" minOccurs="0">
											<simpleType>
												<restriction base="byte">
													<minInclusive value="1" />
													<maxInclusive value="5" />
												</restriction>
											</simpleType>
										</element>
										<element name="tv" type="boolean" />
										<element name="food" minOccurs="0">
											<simpleType>
												<restriction base="string">
													<enumeration value="HB" />
													<enumeration value="BB" />
													<enumeration value="AI" />
												</restriction>
											</simpleType>
										</element>
									</sequence>
								</complexType>
							</element>
						</sequence>
						<attribute name="id" type="string" use="required" />
					</complexType>
				</element>
			</sequence>
		</complexType>
	</element>
</schema>

=== yermochenko/epam-example-of-task3/vauchers.xml
<?xml version="1.0" encoding="UTF-8"?>
<vauchers xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns="http://www.example.org/vauchers" xsi:schemaLocation="http://www.example.org/vauchers vauchers.xsd">
	<vaucher id="a&amp;1">
		<type><![CDATA[тур <выходного> дня]]></type>
		<country>Бразилия</country>
		<days nights="-1">4</days>
		<transport>AVIA</transport>
		<cost>2000</cost>
		<hotel-characteristics>
			<stars>4</stars>
			<tv>true</tv>
			<food>HB</food>
		</hotel-characteristics>
	</vaucher>
	<vaucher id="a&amp;2">
		<type>экскурсионный тур</type>
		<country>Литва</country>
		<days>10</days>
		<transport>RAILWAY</transport>
		<cost>2100</cost>
		<hotel-characteristics>
			<stars>3</stars>
			<tv>false</tv>
		</hotel-characteristics>
	</vaucher>
	<vaucher id="a&amp;3">
		<type>паломничество</type>
		<country>Антарктида</country>
		<days nights="+1">0</days>
		<transport>SHIP</transport>
		<cost>1950</cost>
		<hotel-characteristics>
			<tv>false</tv>
		</hotel-characteristics>
	</vaucher>
</vauchers>
